fn main() {
	println!("Si la commande précedente a retourné des erreurs rien de grave");
}